KTB-15 - send Message
lastbaks/KotlinTelegramBot pull request #12
Opened 2024-08-24 11:34 UTC by lastbaks

В этой задаче у меня возникла достаточно серьезная проблема.
c Regex для получения chatId я разобрался - а вот как в итоге выполнить функцию sendMessage - я понять не смог. Пробовал читать сторонние источники, но пока не разобрался. Если дадите подсказку - буду благодарен.

2024-08-25 08:40 UTC, kaznikit requested changes

2024-08-25 08:40 UTC, kaznikit commented on src/main/kotlin/Telegram.kt
> +        val matchResult: MatchResult? = chatIdRegex.find(updates)
в задании было сказано сделать функцию отправки сообщений `sendMessage`) давай создадим класс `TelegramBotService`, в котором будут функции sendMessage и getUpdates

для отправки сообщения нужно создать url, request и отправить его с помощью httpClient как ты делал в функции getUpdates. если не получится, то пиши в телеге, разберемся

2024-08-25 08:40 UTC, kaznikit commented
> В этой задаче у меня возникла достаточно серьезная проблема. c Regex для получения chatId я разобрался - а вот как в итоге выполнить функцию sendMessage - я понять не смог. Пробовал читать сторонние источники, но пока не разобрался. Если дадите подсказку - буду благодарен.

отписал в коммент

2024-08-26 05:12 UTC, lastbaks commented
Да, у меня как раз не получается "запустить" sendMessage - не пойму, как это сделать. Создать класс и вынести туда отдельные методы, чтобы их потом вызвать - это не проблема. Во вложении код с рефакторингом. В функции sendMessage для теста я печатаю chatId, чтобы видеть, что он выбирается корректно. А вот отправить сообщение не получается.

2024-08-27 04:45 UTC, lastbaks commented
Все, что мы обсуждали, я поправил, в функциях ошибки ушли, но все равно остается вопрос:
Функция getUpdates возвращает строку, и мы ее печатаем.
Функция sendMessage должна отправлять сообщение на сервер, то есть ничего возвращать не надо, нужно в процессе ее
выполнения увидеть в чате сообщение из параметра Ttext, но как его отправить  - у меня в конце функции остается переменная response, которая по факту ничего не делает.

2024-08-27 05:22 UTC, kaznikit requested changes

2024-08-27 05:22 UTC, kaznikit commented on src/main/kotlin/Telegram.kt
>  const val HOST:String = "https://api.telegram.org"
стоит сделать автоформатирование, не хватает пробелов

2024-08-27 05:22 UTC, kaznikit commented on src/main/kotlin/Telegram.kt
> +        telegramBotService.sendMessage(botToken, chatId!!.toInt(), "text to send")
мы не сможем отправить сообщение без chatId, поэтому если он null, то можно сделать просто continue
`val chatId = groups?.get(1)?.value ?: continue`

2024-08-27 05:22 UTC, kaznikit commented on src/main/kotlin/Telegram.kt
> +        return (response.body())
скобки можно убрать

2024-08-27 05:22 UTC, kaznikit commented on src/main/kotlin/Telegram.kt
> +        val response: HttpResponse<String> = client.send(request, HttpResponse.BodyHandlers.ofString())
можно удалить респонз раз мы его не используем

2024-08-27 05:22 UTC, kaznikit commented on src/main/kotlin/Telegram.kt
> +
пустые строчки можно почистить

2024-08-27 17:42 UTC, lastbaks commented on src/main/kotlin/Telegram.kt
> +
Все, я более менее разобрался, функцию sendMessage запустил, добавил выполнение условия проверки, что ввел пользователь, и если введено Hello, то бот говорит Hello в ответ.

2024-08-28 05:40 UTC, kaznikit approved these changes

2024-08-28 06:10 UTC, merged