KTB-16 - разработка кнопок и отправка их в чат
lastbaks/KotlinTelegramBot pull request #13
Opened 2024-08-29 05:20 UTC by lastbaks

Сделал задание + оптимизировал код по примеру видео - вынос всех regex в отдельный блок и за пределы while - true оказалось приятным. Код явно лучше воспринимается.

2024-08-29 12:40 UTC, kaznikit requested changes

2024-08-29 12:40 UTC, kaznikit commented on src/main/kotlin/Telegram.kt
> +    val HOST: String = "https://api.telegram.org"
давай добавим const, чтобы сделать ее константой (в этом случае нужен будет companion object) или назовем с маленькой буквы, так как переменные заглавными буквами называть не принято)

2024-08-29 12:40 UTC, kaznikit commented on src/main/kotlin/Telegram.kt
> +        if (data?.lowercase() == "statictics_clicked" && chatId != null) {
давай вынесем в константу `statictics_clicked`

2024-08-29 12:40 UTC, kaznikit commented on src/main/kotlin/Telegram.kt
> +                                "callback_data": "learn_words_clicked"
и здесь тоже стоит вынести в константы

2024-08-29 14:32 UTC, lastbaks commented on src/main/kotlin/Telegram.kt
> +    val HOST: String = "https://api.telegram.org"
Лучше тут сделаем с маленькой буквы, чтобы не уходить далеко от примера кода.

2024-08-29 14:32 UTC, lastbaks commented on src/main/kotlin/Telegram.kt
> +        if (data?.lowercase() == "statictics_clicked" && chatId != null) {
Готово.

2024-08-29 14:32 UTC, lastbaks commented on src/main/kotlin/Telegram.kt
> +                                "callback_data": "learn_words_clicked"
Готово.

2024-08-30 05:38 UTC, kaznikit approved these changes

2024-08-30 05:39 UTC, merged