KTB-17 - Отправка статистики
lastbaks/KotlinTelegramBot pull request #14
Opened 2024-08-30 21:22 UTC by lastbaks

2024-08-31 07:34 UTC, kaznikit requested changes

2024-08-31 07:34 UTC, kaznikit commented on src/main/kotlin/Main.kt
> +//data class Word(
комментированный код не стоит оставлять, если на то нет веских причин)

2024-08-31 20:30 UTC, lastbaks commented on src/main/kotlin/Main.kt
> +//data class Word(
тут код оставлен в процессе переноса. после переноса будет удален.

2024-09-01 05:56 UTC, kaznikit approved these changes

2024-09-02 03:51 UTC, merged