KTB-18 - реализация функционала изучения слов
lastbaks/KotlinTelegramBot pull request #15
Opened 2024-09-03 04:20 UTC by lastbaks

Функционал я перенес, единственное я не понял, как сделать пункт 4 из задания:

Вынести логику внутри условия if в функцию checkNextQuestionAndSend(trainer: LearnWordsTrainer, botToken: String, chatId: Int). Эта логика понадобится при обработке ответов пользователя.

2024-09-04 08:57 UTC, kaznikit requested changes

2024-09-04 08:57 UTC, kaznikit commented on src/main/kotlin/Telegram.kt
> +            if (question == null) {
давай код из этого if перенесем в функцию `checkNextQuestionAndSend` в `TelegramBotService`. про это говорилось в 4 пункте задания)

2024-09-04 08:57 UTC, kaznikit commented
> Функционал я перенес, единственное я не понял, как сделать пункт 4 из задания:
> 
> Вынести логику внутри условия if в функцию checkNextQuestionAndSend(trainer: LearnWordsTrainer, botToken: String, chatId: Int). Эта логика понадобится при обработке ответов пользователя.

ответил в комменте

2024-09-04 19:31 UTC, lastbaks commented on src/main/kotlin/Telegram.kt
> +            if (question == null) {
В таком виде да - функцию добавить можно, только она отрабатывает целиком выдачу вопроса - как я и предполагал. выложил исправленный код.

2024-09-05 05:40 UTC, kaznikit approved these changes

2024-09-06 21:59 UTC, merged