KTB-21 - Многопользовательский режим + сброс статистики.
lastbaks/KotlinTelegramBot pull request #18
Opened 2024-09-14 19:38 UTC by lastbaks

2024-09-15 12:53 UTC, kaznikit requested changes

2024-09-15 12:53 UTC, kaznikit commented on src/main/kotlin/Word.kt
> +//data class Word(
а этот класс еще для чего то нужен? может лучше почистить закомментированный код?

2024-09-15 12:53 UTC, kaznikit commented on src/main/kotlin/Telegram.kt
> +var correctAnswerTranslate = "" // тут переменная
это переменная, но расположена она на уровне констант. вообще судя по коду она используется только в функции `handleUpdate`, может ее там и создавать?

2024-09-15 12:53 UTC, kaznikit commented on src/main/kotlin/Main.kt
> +//далее код из файла телеграм кт
не понимаю зачем здесь такой большой кусок закомментированного кода? если он не нужен давай его удалим

2024-09-15 18:33 UTC, lastbaks commented on src/main/kotlin/Word.kt
> +//data class Word(
На данном этапе уже не нужен. Очистил код, и удалил сам файл, т.к. он больше ничего не содержал.

2024-09-15 19:31 UTC, lastbaks commented on src/main/kotlin/Telegram.kt
> +var correctAnswerTranslate = "" // тут переменная
Нет, так не получится. Данная переменная действительно используется только в методе handleUpdate, но так как данный метод создается внутри цикла while, то и переменная будет пересоздаваться заново при каждой итерации цикла, а соответственное не будет сохраняться измененное значение данной переменной, что приведет к неправильному отображению верного ответа при неправильном ответе, но я решил проблему. У меня в классе LearnWordsTrainer переменная question была private, поэтому я не мог к ней обратиться, чтобы получить переменную из класса - приходилось опосредованно через метод ее получать. Теперь переменная correctAnswerTranslate вообще стала не нужна.

2024-09-15 19:35 UTC, lastbaks commented on src/main/kotlin/Main.kt
> +//далее код из файла телеграм кт
Да, теперь этот код можно удалить. Поправил.

2024-09-16 06:57 UTC, kaznikit approved these changes

2024-10-01 15:26 UTC, merged