KTB-11 - создание бота
lastbaks/KotlinTelegramBot pull request #9
Opened 2024-08-19 14:58 UTC by lastbaks

Создание бота, выполнение запросов getMe, getUpdates

2024-08-20 07:19 UTC, kaznikit requested changes

2024-08-20 07:19 UTC, kaznikit commented on src/main/kotlin/Telegram.kt
> +    val urlGetMe = "https://api.telegram.org/bot$botToken/getMe"
давай вынесем хост `https://api.telegram.org` в константу

2024-08-20 07:19 UTC, kaznikit commented on src/main/kotlin/LearnWordsTrainer.kt
> +class LearnWordsTrainer(private val learnedAnswerCount: Int = 3, private val requireAnswerCount: Int = 3, private val countOfQuestionWords: Int = 4,) {
попробуй сделать автоформатирование, слишком длинная строка получается

2024-08-20 09:00 UTC, lastbaks commented on src/main/kotlin/LearnWordsTrainer.kt
> +class LearnWordsTrainer(private val learnedAnswerCount: Int = 3, private val requireAnswerCount: Int = 3, private val countOfQuestionWords: Int = 4,) {
Автоформат ничего не меняет. Сделал расстановку полей по отдельным строкам вручную.

2024-08-20 17:50 UTC, lastbaks commented on src/main/kotlin/Telegram.kt
> +    val urlGetMe = "https://api.telegram.org/bot$botToken/getMe"
Поправил, но вообще считаю это не очень хорошим вариантом, т.к. в уроке это в константу не выводится, а далее на основании этого урока делаются другие, и чем больше изменений относительно урока, тем сложнее воспринимать обучение.

2024-08-21 08:03 UTC, kaznikit commented on src/main/kotlin/Telegram.kt
> +    val urlGetMe = "https://api.telegram.org/bot$botToken/getMe"
это не что-то критичное и носит больше рекомендательный характер. просто если одно и то же значение используется в коде 2 раза и более, то желательно выносить его в переменную или константу во избежание ошибок)

2024-08-21 08:04 UTC, kaznikit approved these changes

2024-08-21 08:23 UTC, merged